@endpoint =  https://vast-everglades-45984.herokuapp.com/api/persons



GET {{endpoint}}

###
GET {{endpoint}}/6


###
POST {{endpoint}}
Content-Type: application/json

{
    "name": "abdulsamad",
    "number": "345212434"
}

###
DELETE {{endpoint}}/3